id: I9D361F72
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T12:34:12+00:00'
last_modified: '2022-06-15T13:58:23.476837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS61414
  title: གཞི་ལམ་འབྲས་གསུམ་ལས་བརྩམས་པའི་དྲིས་ལན་ཡིད་ཀྱི་མུན་སེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5655':
      image_group_id: I1GS61416
      title: Volume 1 of gzhi lam 'bras gsum las brtsams pa'i dris lan yid kyi mun
        sel
      total_pages: 150
      order: 1
      base_file: 5655.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
